/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsproje;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author nisaaktas
 */
public class NisaAktasArayüz_start1 extends javax.swing.JFrame {

    /**
     * Creates new form Arayüz_start1
     */
    public NisaAktasArayüz_start1() {
        initComponents();
   // 1. BOYUT: 
    int size = 800;
    this.setSize(size, size);
    this.setLocationRelativeTo(null);
    this.setResizable(false);

    try {
        // 2. RESİM: 800x800 olarak yeniden boyutlandır
        java.net.URL resimURL = getClass().getResource("/dsproje/arkaplan2.png");
        if (resimURL != null) {
            ImageIcon icon = new ImageIcon(resimURL);
            Image img = icon.getImage().getScaledInstance(size, size, Image.SCALE_SMOOTH);
            icon_lbl.setIcon(new ImageIcon(img));
            icon_lbl.setBounds(0, 0, size, size);
            icon_lbl.setText("");
        }

        // 3. SİLİKLEŞTİRME (Karartma Paneli)
        karartma_pnl.setBackground(new java.awt.Color(0, 0, 0, 170)); // Biraz kararttık ki yazı parlasın
        karartma_pnl.setBounds(0, 0, size, size);
        karartma_pnl.setOpaque(true);

        // 4. YAZI: "DROP NUMBER GAME" (800'e göre ortalıyoruz)
        oyun_ad.setText("DROP NUMBER ");
        oyun_ad.setFont(new java.awt.Font("Georgia", java.awt.Font.BOLD, 55)); // Fontu da biraz küçülttük
        oyun_ad.setForeground(java.awt.Color.WHITE);
        oyun_ad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oyun_ad.setBounds(0, 250, size, 100);

        // 5. BUTON: "START GAME" (Tam alt-ortada)
        start_bttn.setText("START GAME");
        start_bttn.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 24));
        start_bttn.setBounds(275, 600, 250, 60); // 800'lük ekranda tam orta: (800-250)/2 = 275

        // 6. KATMANLARI KİLİTLE (Sıralama asla bozulmasın)
        this.getLayeredPane().setComponentZOrder(oyun_ad, 0);
        this.getLayeredPane().setComponentZOrder(start_bttn, 1);
        this.getLayeredPane().setComponentZOrder(karartma_pnl, 2);
        this.getLayeredPane().setComponentZOrder(icon_lbl, 3);

        this.repaint();
    } catch (Exception e) {
        System.out.println("Hata: " + e.getMessage());
    }
}
     
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        karartma_pnl = new javax.swing.JPanel();
        icon_lbl = new javax.swing.JLabel();
        oyun_ad = new javax.swing.JLabel();
        start_bttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout karartma_pnlLayout = new javax.swing.GroupLayout(karartma_pnl);
        karartma_pnl.setLayout(karartma_pnlLayout);
        karartma_pnlLayout.setHorizontalGroup(
            karartma_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        karartma_pnlLayout.setVerticalGroup(
            karartma_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(karartma_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        icon_lbl.setText("jLabel2");
        icon_lbl.setMaximumSize(new java.awt.Dimension(1122, 1122));
        icon_lbl.setMinimumSize(new java.awt.Dimension(1122, 1122));
        getContentPane().add(icon_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        oyun_ad.setText("jLabel3");
        getContentPane().add(oyun_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        start_bttn.setText("jButton1");
        start_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(start_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_bttnActionPerformed
        // TODO add your handling code here:
        new NisaAktasArayüz_start2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_start_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_start1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_start1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_start1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_start1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NisaAktasArayüz_start1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_lbl;
    private javax.swing.JPanel karartma_pnl;
    private javax.swing.JLabel oyun_ad;
    private javax.swing.JButton start_bttn;
    // End of variables declaration//GEN-END:variables
}
