/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsproje;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author nisaaktas
 */
public class NisaAktasArayüz_start2 extends javax.swing.JFrame {

    /**
     * Creates new form Arayüz_start2
     */
    public NisaAktasArayüz_start2() {
        initComponents();
     // 1. Ekranı 800x800 yap ve tam ortala
    this.setSize(800, 800);
    this.setLocationRelativeTo(null);
    this.setResizable(false);

    try {
        // 2. ARKA PLAN: Giriş ekranıyla aynı resmi kullan (Tutarlılık!)
        java.net.URL resimURL = getClass().getResource("/dsproje/arkaplan2.png");
        if (resimURL != null) {
            ImageIcon icon = new ImageIcon(resimURL);
            Image img = icon.getImage().getScaledInstance(800, 800, Image.SCALE_SMOOTH);
            resim.setIcon(new ImageIcon(img));
            resim.setBounds(0, 0, 800, 800);
            resim.setText("");
        }

        // 3. SİLİKLEŞTİRME (Resmi biraz daha karartalım ki yazılar okunsun)
        karartma.setBackground(new java.awt.Color(0, 0, 0, 200)); // 200 daha koyu ve asil durur
        karartma.setBounds(0, 0, 800, 800);
       karartma.setOpaque(true);

        // 4. BİLGİLENDİRME YAZILARI (HTML ile alt alta ve ortalı)
        yazı.setText("<html><center><h1 style='color:white;'>HOW TO PLAY?</h1><br>"
    + "<p style='font-size:14px;'>1. Press <b>SPACE</b> to execute the next move from the scenario.</p><br>"
    + "<p style='font-size:14px;'>2. Watch the <b>automatic placement</b> and <b>vertical merges</b>.</p><br>"
    + "<p style='font-size:14px;'>3. Follow the steps until the scenario is completed.</p><br>"
    + "</center></html>"
);
        yazı.setForeground(java.awt.Color.WHITE);
        yazı.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yazı.setBounds(50, 150, 700, 400); // Yazıyı ekrana yaydık, tam ortada duracak

        // 5. BUTON: "ANLADIM"
        start_bttn.setText("START GAME");
        start_bttn.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
        start_bttn.setBounds(275, 600, 250, 60); // Tam alt-orta

        // 6. KATMAN SIRALAMASI (Yazılar kaybolmasın)
        this.getLayeredPane().setComponentZOrder(yazı, 0); // Yazılar en önde
        this.getLayeredPane().setComponentZOrder(start_bttn, 1); // Buton üstte
        this.getLayeredPane().setComponentZOrder(karartma, 2); // Karartma ortada
        this.getLayeredPane().setComponentZOrder(resim, 3); // Resim en arkada

    } catch (Exception e) {
        System.out.println("Bilgilendirme ekranı hatası: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resim = new javax.swing.JLabel();
        karartma = new javax.swing.JPanel();
        yazı = new javax.swing.JLabel();
        start_bttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resim.setText("jLabel2");
        getContentPane().add(resim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        javax.swing.GroupLayout karartmaLayout = new javax.swing.GroupLayout(karartma);
        karartma.setLayout(karartmaLayout);
        karartmaLayout.setHorizontalGroup(
            karartmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        karartmaLayout.setVerticalGroup(
            karartmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(karartma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        yazı.setText(" HOW TO PLAY ");
        getContentPane().add(yazı, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 150, 50));

        start_bttn.setText("jButton2");
        start_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_bttnActionPerformed(evt);
            }
        });
        getContentPane().add(start_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_bttnActionPerformed
        // TODO add your handling code here:
        NisaAktasArayüz_grid a=new NisaAktasArayüz_grid();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_start_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_start2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_start2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_start2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_start2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NisaAktasArayüz_start2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel karartma;
    private javax.swing.JLabel resim;
    private javax.swing.JButton start_bttn;
    private javax.swing.JLabel yazı;
    // End of variables declaration//GEN-END:variables
}
