/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsproje;

import java.awt.Color;
import java.awt.event.ActionEvent;

/**
 *
 * @author nisaaktas
 */
public class NisaAktasArayüz_grid extends javax.swing.JFrame {

    //35 tane label dızının ıcınde
    private javax.swing.JLabel[] tumHucreler = new javax.swing.JLabel[35];
    NisaAktasGame game;
    //hangı sutuna gıdılecegının sutunları
    int[] sutunSenaryosu = {0, 3, 1, 2, 4, 1, 4, 0, 0, 1, 2, 2, 3, 1, 2, 0, 4, 2, 1, 3, 3, 3, 3, 1, 2, 2, 2, 2, 2, 1, 1};
    int hamleIndex = 0;

    /**
     * Creates new form Arayüz
     */
    public NisaAktasArayüz_grid() {

        initComponents();
        gameOverAyarları(); //oyun bıttı ekranını panele ekle

        this.setLocationRelativeTo(null); //pencere ekranın ortasında 
        this.setResizable(false);
        this.game = new NisaAktasGame();

        this.setFocusable(true);  //space algılasın dıye 

        //labellerı tumhucreler dızısıne ekler 
        //hucrelere ındıs uzerınden erısır 
        java.awt.Component[] bilesenler = hücre_pnl.getComponents();
        tumHucreler = new javax.swing.JLabel[bilesenler.length];

        for (int i = 0; i < bilesenler.length; i++) {
            tumHucreler[i] = (javax.swing.JLabel) bilesenler[i];
        }
        updateGUI(); //ilk durum getırme 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hücre_pnl = new javax.swing.JPanel();
        hücre1 = new javax.swing.JLabel();
        hücre8 = new javax.swing.JLabel();
        hücre15 = new javax.swing.JLabel();
        hücre22 = new javax.swing.JLabel();
        hücre29 = new javax.swing.JLabel();
        hücre2 = new javax.swing.JLabel();
        hücre9 = new javax.swing.JLabel();
        hücre16 = new javax.swing.JLabel();
        hücre23 = new javax.swing.JLabel();
        hücre30 = new javax.swing.JLabel();
        hücre3 = new javax.swing.JLabel();
        hücre10 = new javax.swing.JLabel();
        hücre17 = new javax.swing.JLabel();
        hücre24 = new javax.swing.JLabel();
        hücre31 = new javax.swing.JLabel();
        hücre4 = new javax.swing.JLabel();
        hücre11 = new javax.swing.JLabel();
        hücre18 = new javax.swing.JLabel();
        hücre25 = new javax.swing.JLabel();
        hücre32 = new javax.swing.JLabel();
        hücre5 = new javax.swing.JLabel();
        hücre12 = new javax.swing.JLabel();
        hücre19 = new javax.swing.JLabel();
        hücre26 = new javax.swing.JLabel();
        hücre33 = new javax.swing.JLabel();
        hücre6 = new javax.swing.JLabel();
        hücre13 = new javax.swing.JLabel();
        hücre20 = new javax.swing.JLabel();
        hücre27 = new javax.swing.JLabel();
        hücre34 = new javax.swing.JLabel();
        hücre7 = new javax.swing.JLabel();
        hücre14 = new javax.swing.JLabel();
        hücre21 = new javax.swing.JLabel();
        hücre28 = new javax.swing.JLabel();
        hücre35 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        next_lbl = new javax.swing.JLabel();
        game_over_pnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        hücre_pnl.setLayout(new java.awt.GridLayout(7, 5));

        hücre1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre1.setName(""); // NOI18N
        hücre1.setOpaque(true);
        hücre1.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre1);

        hücre8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre8.setOpaque(true);
        hücre8.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre8);

        hücre15.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre15.setOpaque(true);
        hücre15.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre15);

        hücre22.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre22.setOpaque(true);
        hücre22.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre22);

        hücre29.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre29.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre29.setOpaque(true);
        hücre29.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre29);

        hücre2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre2.setOpaque(true);
        hücre2.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre2);

        hücre9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre9.setOpaque(true);
        hücre9.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre9);

        hücre16.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre16.setOpaque(true);
        hücre16.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre16);

        hücre23.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre23.setOpaque(true);
        hücre23.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre23);

        hücre30.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre30.setOpaque(true);
        hücre30.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre30);

        hücre3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre3.setOpaque(true);
        hücre3.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre3);

        hücre10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre10.setOpaque(true);
        hücre10.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre10);

        hücre17.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre17.setOpaque(true);
        hücre17.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre17);

        hücre24.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre24.setOpaque(true);
        hücre24.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre24);

        hücre31.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre31.setOpaque(true);
        hücre31.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre31);

        hücre4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre4.setOpaque(true);
        hücre4.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre4);

        hücre11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre11.setOpaque(true);
        hücre11.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre11);

        hücre18.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre18.setOpaque(true);
        hücre18.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre18);

        hücre25.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre25.setOpaque(true);
        hücre25.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre25);

        hücre32.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre32.setOpaque(true);
        hücre32.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre32);

        hücre5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre5.setOpaque(true);
        hücre5.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre5);

        hücre12.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre12.setOpaque(true);
        hücre12.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre12);

        hücre19.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre19.setOpaque(true);
        hücre19.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre19);

        hücre26.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre26.setOpaque(true);
        hücre26.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre26);

        hücre33.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre33.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre33.setOpaque(true);
        hücre33.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre33);

        hücre6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre6.setOpaque(true);
        hücre6.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre6);

        hücre13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre13.setOpaque(true);
        hücre13.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre13);

        hücre20.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre20.setOpaque(true);
        hücre20.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre20);

        hücre27.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre27.setOpaque(true);
        hücre27.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre27);

        hücre34.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre34.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre34.setOpaque(true);
        hücre34.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre34);

        hücre7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre7.setOpaque(true);
        hücre7.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre7);

        hücre14.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre14.setOpaque(true);
        hücre14.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre14);

        hücre21.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre21.setOpaque(true);
        hücre21.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre21);

        hücre28.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre28.setOpaque(true);
        hücre28.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre28);

        hücre35.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hücre35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hücre35.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hücre35.setOpaque(true);
        hücre35.setPreferredSize(new java.awt.Dimension(60, 60));
        hücre_pnl.add(hücre35);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        next_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        next_lbl.setText("jLabel1");
        jPanel3.add(next_lbl);

        javax.swing.GroupLayout game_over_pnlLayout = new javax.swing.GroupLayout(game_over_pnl);
        game_over_pnl.setLayout(game_over_pnlLayout);
        game_over_pnlLayout.setHorizontalGroup(
            game_over_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        game_over_pnlLayout.setVerticalGroup(
            game_over_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 503, Short.MAX_VALUE)
                .addComponent(game_over_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addComponent(hücre_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(game_over_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106)
                .addComponent(hücre_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

        char key = evt.getKeyChar();

        //space basınca ve henuz senaryo bıtmemısse           
        if (key == ' ' && game.nextValue != null && hamleIndex < sutunSenaryosu.length) {

            // Sütunu biz seçmiyoruz, diziden sırayla geliyor!
            //sıradakı sutunu alıyor bunu colındex yapıyır
            int colIndex = sutunSenaryosu[hamleIndex];
            hamleIndex++;

            //taşı secılen sutuna bırak 
            game.dropTile(colIndex);

            game.nextValue = game.generateNextValue();
            updateGUI(); //gorunumu guncelle 

            //merge ıslemı ıcın tımer kullanıyor 
            javax.swing.Timer timer = new javax.swing.Timer(500, null);
            timer.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    //bırlesecek tas varsa merged true 
                    boolean merged = game.merge(colIndex); //merge bırlesme olursa true döndürür
                    updateGUI(); //guı guncelle 
                    //bırlesecek tas yoksa tımer durdur yenı tas uret 
                    if (!merged) {
                        ((javax.swing.Timer) e.getSource()).stop();

                        updateGUI();
                    }
                }
            });
            timer.start();

        }


    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_grid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_grid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_grid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NisaAktasArayüz_grid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NisaAktasArayüz_grid().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel game_over_pnl;
    private javax.swing.JLabel hücre1;
    private javax.swing.JLabel hücre10;
    private javax.swing.JLabel hücre11;
    private javax.swing.JLabel hücre12;
    private javax.swing.JLabel hücre13;
    private javax.swing.JLabel hücre14;
    private javax.swing.JLabel hücre15;
    private javax.swing.JLabel hücre16;
    private javax.swing.JLabel hücre17;
    private javax.swing.JLabel hücre18;
    private javax.swing.JLabel hücre19;
    private javax.swing.JLabel hücre2;
    private javax.swing.JLabel hücre20;
    private javax.swing.JLabel hücre21;
    private javax.swing.JLabel hücre22;
    private javax.swing.JLabel hücre23;
    private javax.swing.JLabel hücre24;
    private javax.swing.JLabel hücre25;
    private javax.swing.JLabel hücre26;
    private javax.swing.JLabel hücre27;
    private javax.swing.JLabel hücre28;
    private javax.swing.JLabel hücre29;
    private javax.swing.JLabel hücre3;
    private javax.swing.JLabel hücre30;
    private javax.swing.JLabel hücre31;
    private javax.swing.JLabel hücre32;
    private javax.swing.JLabel hücre33;
    private javax.swing.JLabel hücre34;
    private javax.swing.JLabel hücre35;
    private javax.swing.JLabel hücre4;
    private javax.swing.JLabel hücre5;
    private javax.swing.JLabel hücre6;
    private javax.swing.JLabel hücre7;
    private javax.swing.JLabel hücre8;
    private javax.swing.JLabel hücre9;
    private javax.swing.JPanel hücre_pnl;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel next_lbl;
    // End of variables declaration//GEN-END:variables

    //tum  labelları temızler  
    private void temizle(int index) {

        if (index >= 35) {
            return;
        }
        //labelın textını "" yapar arkaplanı beyaz yapar 
        tumHucreler[index].setText("");
        tumHucreler[index].setBackground(Color.white);
        //diğer labelı ıcın aynı yapılsın dıye onu cagırırı 
        temizle(index + 1);

        //gerı donerken labelların yazı rengını sıyah yapar 
        tumHucreler[index].setForeground(java.awt.Color.BLACK);
    }


    /* private void hucreDoldur(NisaAktasNode<Integer> node, int colIndex, int rowIndex) {
        if (node == null || rowIndex < 0) {
            return;
        }
        int labelIndex = (rowIndex * 5) + colIndex;

        if (labelIndex >= 0 && labelIndex < tumHucreler.length) {
            tumHucreler[labelIndex].setText(node.value.toString());
            renklendir(tumHucreler[labelIndex], node.value);
        }

        hucreDoldur(node.down, colIndex, rowIndex - 1);

    }*/
//degere gore labellerı renklendırır 
    private void renklendir(javax.swing.JLabel label, int value) {
        switch (value) {
            case 2:
                label.setBackground(Color.YELLOW);
                label.setForeground(Color.BLACK);
                break;
            case 4:
                label.setBackground(Color.ORANGE);
                break;
            case 8:
                label.setBackground(Color.GREEN);
                break;
            case 16:
                label.setBackground(Color.magenta);
                label.setForeground(Color.white);
                break;
            case 32:
                label.setBackground(Color.CYAN);
                label.setForeground(Color.BLACK);
                break;
            case 64:
                label.setBackground(Color.BLUE);
                label.setForeground(Color.white);
                break;
            case 128:
                label.setBackground(Color.RED);
                label.setForeground(Color.white);
                break;
            case 256:
                label.setBackground(Color.PINK);
                label.setForeground(Color.red);
                break;
            default:
                break;
        }

    }

    private void updateGUI() {
        temizle(0); //hucrelerı temızle

        //multı lınked lıstı headden baslayarak gez 
        NisaAktasNode<Integer> temp = game.head;
        while (temp != null) {
            //sol alt tumhucreler[0] yanı 1 2 3 4 
            //headin hangı tum hucreler[]indexı buldurup hangı labele gıttıgını bulduruyor 
            int labelIndex = ((6 - temp.row) * 5) + temp.col;

            //head ındexındekı labelın rengını textını degıstır 
            if (labelIndex >= 0 && labelIndex < tumHucreler.length) {
                tumHucreler[labelIndex].setText(temp.value.toString());
                renklendir(tumHucreler[labelIndex], temp.value);
                tumHucreler[labelIndex].setVisible(true);

            }
            temp = temp.next;
        }

        if (game.nextValue != null) {

            next_lbl.setText(game.nextValue.toString());
            next_lbl.setOpaque(true);
            renklendir(next_lbl, game.nextValue);
        } else if (!game_over_pnl.isVisible()) {
            next_lbl.setText(("GAME OVER"));

            if (!game_over_pnl.isVisible()) { //game over gorunur degılse 

                new javax.swing.Timer(2000, e -> { //2 sanıye sonra game over panelını goster 
                    game_over_pnl.setVisible(true);
                    game_over_pnl.requestFocus(); //space bastırmaz 
                    ((javax.swing.Timer) e.getSource()).stop(); //tımer durdurur 
                }).start();
            }
        }
        //yapıda değişiklik oldukça gunceletir 
        this.revalidate();
        this.repaint();

    }

    private void gameOverAyarları() {
        game_over_pnl.setBounds(0, 0, 800, 800); //boyut ayarı 
        game_over_pnl.setBackground(new java.awt.Color(0, 0, 0, 180));//panelın matlık ayarı
        game_over_pnl.setLayout(new java.awt.GridBagLayout());//yazı merkeze

        //bıtıs yazısı ayarı 
        javax.swing.JLabel bitisYazisi = new javax.swing.JLabel("GAME OVER");
        bitisYazisi.setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 70));
        bitisYazisi.setForeground(new java.awt.Color(236, 224, 201)); // 

        //  Yazıyı panele ekle
        game_over_pnl.add(bitisYazisi);

        //  Paneli en başta gizle
        game_over_pnl.setVisible(false);

        // 5. ÖNEMLİ: bitisyazisi'nin gridin üstünde görünmesi için LayeredPane 
        this.getLayeredPane().add(game_over_pnl, javax.swing.JLayeredPane.PALETTE_LAYER);
    }

}
